service: certificate-vault-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  environment:
    DB_CERTIFICATE_TABLE: !Ref certificateTable


custom:
  database:
    certificateTable: ${self:service}-users-${self:provider.stage}


plugins:
  - serverless-iam-roles-per-function


functions:
  createCertificate:
    handler: src/functions/certificates/index.createCertificate
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt certificateTable.Arn
    events:
      - http:
          method: post
          cors: true
          path: /v1/certificate


resources:
  Resources:
    certificateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.database.certificateTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: certificate_id
            AttributeType: S
        KeySchema:
          - AttributeName: certificate_id
            KeyType: HASH
